// <auto-generated />
namespace BudgetCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _07April2015a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07April2015a));
        
        string IMigrationMetadata.Id
        {
            get { return "201504071152036_07April2015a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
