// <auto-generated />
namespace BudgetCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _16April2015b : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_16April2015b));
        
        string IMigrationMetadata.Id
        {
            get { return "201504161143541_16April2015b"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
