// <auto-generated />
namespace BudgetCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _08April2015f : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08April2015f));
        
        string IMigrationMetadata.Id
        {
            get { return "201504081459251_08April2015f"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
