// <auto-generated />
namespace BudgetCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _02April2015c : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02April2015c));
        
        string IMigrationMetadata.Id
        {
            get { return "201504021407310_02April2015c"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
